#include "nsISupports.idl"

[scriptable, uuid(e5b1dd2b-f168-4ea0-b0c0-3cee132cbcac)]
interface nsIHeaderTool : nsISupports
{
  string register();
  void   put(in string  key, in string  value);
  void   remove(in string  key);
  void   clear();
};  

